export default [
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        performance: "readonly",
        requestAnimationFrame: "readonly",
        AudioContext: "readonly",
        localStorage: "readonly",
        // Projektkonstanten & -klassen (global via <script>-Tags)
        WORLD_SCALE: "readonly",
        devicePixelRatio: "readonly",
        Boat: "readonly",
        BoatMesh: "readonly",
        Debug: "readonly",
        Input: "readonly",
        Race: "readonly",
        MarksMesh: "readonly",
        Scene: "readonly",
        Sfx: "readonly",
        Tutorial: "readonly",
        UI: "readonly",
        WaterMesh: "readonly",
        Wind: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
      "eqeqeq": "warn",
      "no-var": "error",
    },
  },
];
